# Build settings

port: 4000
markdown:  kramdown
permalink: /:title
plugins:   [jekyll-sitemap, jekyll-feed,  jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)

title:		   "Generative Generation"
description: "Creativity & AI"
author:      "Philipp Haslbauer"
name: "Philipp Haslbauer"
